在游戏开发中，有些异常会游戏无法运行下去，有些异常发生了游戏却可以继续运行，这是怎么回事呢？
因为异常发生了，可能被处理掉了，程序可以继续执行异常之后的代码，因此游戏可以正常运行。有些异常发生了却没有被处理，程序无法执行下去了，游戏就停止运行了。

对于一个异常来说，只要从程序入口点开始到该异常发生的方法中，这一个调用堆栈里，有try catch，就可以对其进行处理。

	try
	{
	}
	finally
	{
	}

上述结构没有catch，如果发生了异常，finally中的语句(默认情况下，一般情况下不会被执行，因为抛出异常，在异常处就停止运行了)不一定会执行。

	try
	{
	}
	catch
	{
	}
	finally
	{
	}

上述结构有catch,对异常进行了处理，finally中的语句一定会执行。

>If the exception is not caught, execution of the finally block depends on whether the operating system chooses to trigger an exception unwind operation
>
>Within a handled exception, the associated finally block is guaranteed to be run. However, if the exception is unhandled, execution of the finally block is dependent on how the exception unwind operation is triggered. That, in turn, is dependent on how your computer is set up. For more information, see [Unhandled Exception Processing in the CLR](http://download.microsoft.com/download/3/a/7/3a7fa450).



	public class ThrowTestA
	{
	    static void Main()
	    {
	        int i = 123;
	        string s = "Some string";
	        object obj = s;
	
	        try
	        {
	            // Invalid conversion; obj contains a string, not a numeric type.
	            i = (int)obj;
	
	            // The following statement is not run.
	            Console.WriteLine("WriteLine at the end of the try block.");
	        }
	        finally
	        {
		            // To run the program in Visual Studio, type CTRL+F5. Then 
		            // click Cancel in the error dialog.
	            Console.WriteLine("\nExecution of the finally block after an unhandled\n" +
	                "error depends on how the exception unwind operation is triggered.");
	            Console.WriteLine("i = {0}", i);
	        }
	    }
	    // Output:
	    // Unhandled Exception: System.InvalidCastException: Specified cast is not valid.
	    //
	    // Execution of the finally block after an unhandled
	    // error depends on how the exception unwind operation is triggered.
	    // i = 123
	}
